### ISSUE TITLE
Alpha Demo v0.1.0 roadmap

### ISSUE THREAD

**Issue by ShaeTsuPog** [ShaeTsuPog/em-vstar#11]
- [ ] Story
- [ ] Mapping
	- [ ] Polish starting town
	- [ ] Route 1
	- [x] Side Area Forest
	- [ ] Second Town
	- [ ] Cave/Mine
	- [ ] First Gym Town

- [ ] Encounter table tuning
- [ ] Add new region map
- [ ] **_FIX REGION MAP SCROLLING_**
- [ ] Polish the following UIs
	- [ ] Move selection info
	- [ ] Party menu
	- [ ] PC menus
- [ ] Theme the following UIs
	- [ ] TM Case
	- [ ] DexNav
	- [ ] PokeNav
	- [ ] Start Menu
